#!/bin/bash

#FUERA DE UN ENTORNO VIRTUAL
#ejecutar $sudo ./scrpt_pau

apt-get update && apt-get upgrade -y
apt-get install python3-pip python3-graphviz python3-tk -y
apt-get update && apt-get upgrade -y
apt autoremove -y
