#!/bin/bash

#ejecutar $ ./scrpt_pips
pip3 install bokeh==2.2.3 dask==2.30.0 distributed==2.30.0 fastparquet==0.4.1 graphviz==0.8.4 h5py==2.10.0 hdf5plugin==2.3.2 llvmlite==0.33.0 matplotlib==3.3.2 numba==0.50.1 numpy==1.19.2 pandas==1.1.3 psutil==5.7.2 scipy==1.5.2 tqdm==4.50.2 terminaltables==3.1.0
